### ISSUE TITLE
sandbox tests started to fail

### ISSUE THREAD

**Issue by eserte** [singingfish/braintree_perl#22]
Looking at http://matrix.cpantesters.org/?dist=WebService-Braintree%201.1;reports=1#sl=7,1 there are no more pass reports recently. It seems that the sandbox tests are failing. A sample fail report: http://www.cpantesters.org/cpan/report/5dadcdbc-2ecf-11e8-828a-befe28307975

**Comment by singingfish** [comment]
looks like this was due to a sandbox_config.json being distributed accidentally.  Now not distributed so the tests should skip
