### ISSUE TITLE
Transaction->submit_for_settlement broken by validation added in 1.3

### ISSUE THREAD

**Issue by ssimms** [singingfish/braintree_perl#27]
I'm getting an ArgumentError when calling:

`WebService::Braintree::Transaction->submit_for_settlement($order_id, $amount);`

The code in that module sets `$params->{'amount'}` to `$amount`, and then calls the equivalently-named method in WebService::Braintree::TransactionGateway.  That method has a new verify_params call that doesn't have "amount" on its whitelist, which appears to be causing the failure.

On a related note, all three of submit_for_settlement, update_details, and submit_for_partial_settlement have "description" in their whitelist, whereas Braintree appears to be expecting "descriptor" (based on looking at the API docs and the equivalent Ruby gem -- I haven't actually tried using these fields).

**Comment by robkinyon** [comment]
I'm really sorry for introducing these issues. #29 should fix them (including the description/descriptor mistake). Thank you so much for reporting this!

**Comment by singingfish** [comment]
due dilligence applied, fix merged, pushed and updated on cpan to version 1.5
