### ISSUE TITLE
Initialising using Object Notation

### ISSUE THREAD

**Issue by Zhadnost** [singingfish/braintree_perl#32]
When trying to use object notation (as per perldoc), Gateway tries to call WebService::Braintree::Config instead of WebService::Braintree::Configuration. (Fails, unable to find new).

Line 46 on Gateway.pm states:

            config => WebService::Braintree::Config->new( $args ),

Should read:

            config => WebService::Braintree::Configuration->new( $args ),

**Comment by dr-kd** [comment]
Thanks for finding this.  Fixed and released to cpan as v 1.7
