### ISSUE TITLE
Missing Dependency

### ISSUE THREAD

**Issue by Zhadnost** [singingfish/braintree_perl#33]
Installing from cpan fails requiring Moose::Role.
Installing Moose::Role before WebService::Braintree is a suitable workaround.

**Comment by dr-kd** [comment]
Thanks for bringing this to my attention.  Moose::Role should not be required but had not been replaced with Moo::Role in a few places.   had prepared the fix but forgotten to release to the cpan.  Now it's released as v 1.7 on the cpan
